# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Kernel.php'
            
    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/Entity/'
            
    Infrastructure\:
        resource: '../src/Infrastructure'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ## App
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            
    App\Service\JWT\TokenService:
        arguments:
            $secret: '%env(resolve:APP_SECRET)%'
            
    App\Service\Security\AuthenticationService:
        arguments:
            $tokenLifetime: '%env(resolve:TOKEN_LIFETIME)%'
            
    array_denormalizer:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
        tags: [serializer.normalizer]

    ## Domain
    Domain\Repository\AttributeRepositoryInterface: '@Domain\Repository\AttributeRepository'
    Domain\Repository\UserRepositoryInterface: '@Domain\Repository\UserRepository'
    Domain\Repository\CategoryRepositoryInterface: '@Domain\Repository\CategoryRepository'
    Domain\Repository\ProductRepositoryInterface: '@Domain\Repository\ProductRepository'
    
    Domain\Service\Product\CreateProductServiceInterface: '@Domain\Service\Product\CreateProductService'
    Domain\Service\Product\UpdateProductServiceInterface: '@Domain\Service\Product\UpdateProductService'
    Domain\Service\Product\DeleteProductServiceInterface: '@Domain\Service\Product\DeleteProductService'
    Domain\Service\Category\CreateCategoryServiceInterface: '@Domain\Service\Category\CreateCategoryService'
    Domain\Service\User\CreateUserServiceInterface: '@Domain\Service\User\CreateUserService'
    
    ## Infrastructure
    Domain\Service\User\UserPasswordEncoderInterface: '@Infrastructure\Service\User\UserPasswordEncoder'
    